---
- hosts: servers
  gather_facts: yes
  vars:
    user: "{{ ansible_user }}"
    home_dir: "/home/{{ user }}"
  become: yes
  tasks:
    
       ## SUPERSET
    - name: check if superset environment is present
      stat: path={{ home_dir }}/archiconda3/envs/superset/bin/python
      register: superset

    - name: setup superset conda-env
      expect:
        command: "{{ home_dir }}/archiconda3/bin/conda create --name superset python=3.7.1"
        responses:
            'Proceed': 'y'
        timeout: 36000
      when: superset.stat.exists == False

    - name: install pandas (conda-forge)
      expect:
        command: "{{ home_dir }}/archiconda3/bin/conda install --name superset -c conda-forge pandas==1.2.4"
        responses:
            'Proceed': 'y'
        timeout: 36000
      when: superset.stat.exists == False

    - name: install pyarrow (conda-forge)
      expect:
        command: "{{ home_dir }}/archiconda3/bin/conda install --name superset -c conda-forge pyarrow==3.0.0"
        responses:
            'Proceed': 'y'
        timeout: 36000
      when: superset.stat.exists == False

    - name: upgrade pip
      pip: 
        name: pip
        executable: "{{ home_dir }}/archiconda3/envs/superset/bin/pip"
        state: latest
    
    - name: install superset
      pip: 
        name: "{{ item }}"
        executable: "{{ home_dir }}/archiconda3/envs/superset/bin/pip"
      loop:
        - setuptools
        - mysqlclient
        - PyJWT
        - apache-superset

    - name: upgrade superset db
      command: "{{ home_dir }}/archiconda3/envs/superset/bin/superset db upgrade"


    - name: create superset user
      command: "{{ home_dir }}/archiconda3/envs/superset/bin/superset fab create-admin --username admin --firstname Maximilian \
            --lastname Pichler --email {{ user }}@{{ user }}.com --password abcd"
      environment:
        FLASK_APP: superset



    - name: initialize superset
      command: "{{ home_dir }}/archiconda3/envs/superset/bin/superset init"
      environment:
        FLASK_APP: superset

    ## Configure superset service
    - name: Copy the superset.service file
      template: 
        src: superset.txt
        dest: /etc/systemd/system/superset.service
        backup: no
    
    - name: set User
      lineinfile:
        path: "/etc/systemd/system/superset.service"
        regexp: '^User\='
        line: 'User={{ user }}'

    - name: set superset WorkingDirectory
      lineinfile:
        path: "/etc/systemd/system/superset.service"
        regexp: 'WorkingDirectory\='
        line: 'WorkingDirectory={{ home_dir }}'

    - name: set superset executable
      lineinfile:
        path: "/etc/systemd/system/superset.service"
        regexp: 'ExecStart\='
        line: 'ExecStart={{ home_dir }}/archiconda3/envs/superset/bin/superset run -h 0.0.0.0  -p 8088 --reload --debugger'

    - name: Restart superset and enable service at startup
      systemd:
        state: restarted
        enabled: yes
        daemon_reload: yes
        name: superset
