---
- hosts: servers
  gather_facts: yes
  vars:
    user: "{{ ansible_user }}"
    home_dir: "/home/{{ user }}"
  become: yes
  tasks:
    
    - name: check if archiconda folder is present
      stat: path={{ home_dir }}/archiconda3
      register: conda

    - name: Download Archiconda3
      get_url:
        url: https://github.com/Archiconda/build-tools/releases/download/0.2.3/Archiconda3-0.2.3-Linux-aarch64.sh
        dest: "{{ home_dir }}/tmp/Archiconda3-0.2.3-Linux-aarch64.sh"
        mode: '755'
      when: conda.stat.exists == False


    - name: install Archiconda3
      expect:
        command: "{{ home_dir }}/tmp/Archiconda3-0.2.3-Linux-aarch64.sh"
        responses:
            'continue': '\n'
            '27': 'yes'
            'bashrc': 'no'
            'below': '{{ home_dir }}/archiconda3'
        echo: true
        when: conda.stat.exists == False
      no_log: false



    ## SUPERSET
    - name: check if superset folder is present
      stat: path={{ home_dir }}/archiconda3/envs/superset
      register: superset

    - name: setup superset conda-env
        command: "conda create --name superset python=3.7.1"
      when: superset.stat.exists == False




    - name: upgrade pip
        command: "{{ home_dir }}/archiconda3/envs/superset/bin/pip install --upgrade pip"
      when: superset.stat.exists == False

    - name: install pandas (conda-forge)
        command: "{{ home_dir }}/archiconda3/envs/superset/bin/conda install -c conda-forge pandas==1.2.4"
      when: superset.stat.exists == False

    - name: install pyarrow (conda-forge)
        command: "{{ home_dir }}/archiconda3/envs/superset/bin/conda install -c conda-forge pyarrow==3.0.0"
      when: superset.stat.exists == False

    - name: setup superset conda-env
        command: "{{ home_dir }}/archiconda3/envs/superset/bin/pip install apache-superset"
      when: superset.stat.exists == False

      
     - name: Install some packages in the environment
      conda:
        name:
          - superset
        environment: superset

#
#    - name: install pyarrow
#      command: "conda install -c conda-forge pyarrow"

#     - name: Install some packages in the environment
#      conda:
#        name:
#          - superset
#        environment: superset

########################
#conda create --name superset python=3.7.1

#conda update conda
#pip install --upgrade pip

#pip install cffi
#conda install -c conda-forge pandas==1.2.4
#conda install -c conda-forge pyarrow==3.0.0
#pip install apache-superset