---
- hosts: servers
  gather_facts: yes
  vars:
    user: "{{ ansible_user }}"
    home_dir: "/home/{{ user }}"
  become: yes
  tasks:
    
    ## ARCHICONDA
    - name: check if archiconda folder is present
      stat: path={{ home_dir }}/archiconda3/bin
      register: conda

    - name: Download Archiconda3
      get_url:
        url: https://github.com/Archiconda/build-tools/releases/download/0.2.3/Archiconda3-0.2.3-Linux-aarch64.sh
        dest: "{{ home_dir }}/tmp/Archiconda3-0.2.3-Linux-aarch64.sh"
        mode: '755'
      when: conda.stat.exists == False


    - name: install Archiconda3
      expect:
        command: "{{ home_dir }}/tmp/Archiconda3-0.2.3-Linux-aarch64.sh"
        responses:
            'continue': '\n'
            '27': 'yes'
            'bashrc': 'no'
            'below': '{{ home_dir }}/archiconda3'
        echo: true
      when: conda.stat.exists == False
      no_log: false


    ## STREAMING
    - name: check if streaming environment is present
      stat: path={{ home_dir }}/archiconda3/envs/streaming/bin/python
      register: streaming

    - name: setup streaming conda-env
      command: "conda create --name streaming python=3.7.1"
      when: streaming.stat.exists == False

    - name: upgrade pip
      command: "{{ home_dir }}/archiconda3/envs/streaming/bin/pip install --upgrade pip"
      when: streaming.stat.exists == False   

    - name: install requirements.txt
      command: "conda env create --file bio-env.txt "
      when: streaming.stat.exists == False 

    ## SUPERSET
    - name: check if superset environment is present
      stat: path={{ home_dir }}/archiconda3/envs/superset/bin/python
      register: superset

    - name: setup superset conda-env
      command: "conda create --name superset python=3.7.1"
      when: superset.stat.exists == False

    - name: upgrade pip
      command: "{{ home_dir }}/archiconda3/envs/superset/bin/pip install --upgrade pip"
      when: superset.stat.exists == False

    - name: install pandas (conda-forge)
      command: "{{ home_dir }}/archiconda3/envs/superset/bin/conda install -c conda-forge pandas==1.2.4"
      when: superset.stat.exists == False

    - name: install pyarrow (conda-forge)
      command: "{{ home_dir }}/archiconda3/envs/superset/bin/conda install -c conda-forge pyarrow==3.0.0"
      when: superset.stat.exists == False

    - name: install superset
      command: "{{ home_dir }}/archiconda3/envs/superset/bin/pip install apache-superset"
      when: superset.stat.exists == False

      

